# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NearByTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NearByTest

  pod 'NearbyMessages'

  target 'NearByTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NearByTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
